# yamllint configuration
# See https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: true

ignore: |
  .git/
  uv.lock
  node_modules/
  tests/fixtures/
  tests/core/fixtures/
